name: My Second Pipeline

run-name: ${{ github.actor }} is automating workflows with ${{ github.workflow }}

on: 
  push:
    branches: 
      - main

jobs:
  render-figlet-banner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install figlet
        run: sudo apt-get update && sudo apt-get install -y figlet

      - name: Print figlet banner from notes.txt
        run: |
          TEXT="$(cat notes.txt)"
          figlet "$TEXT"

  render-cowsay-banner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Print cowsay banner from notes.txt
        run: |
          TEXT="$(cat notes.txt)"
          cowsay "$TEXT"
